INSERT INTO word (id,english_word, russian_translation, topic) VALUES
(1,'Traffic lights', 'Светофор', 'City'),
(2,'Street', 'Улица', 'City'),
(3,'Square', 'Площадь', 'City'),
(4,'Zebra crossing', 'Зебра', 'City'),
(5,'Pavement', 'Тротуар', 'City'),
(6,'Park', 'Парк', 'City'),
(7,'Railway station', 'Железнодорожная станция', 'City'),
(8,'Bar', 'Бар', 'City'),
(9,'Cafe', 'Кафе', 'City'),
(10,'Factory', 'Фабрика', 'City'),
(11,'Supermarket', 'Супермаркет', 'City'),
(12,'Cinema', 'Кинотеатр', 'City'),
(13,'Bank', 'Банк', 'City'),
(14,'Post office', 'Почта', 'City'),
(15,'School', 'Школа', 'City'),
(16,'Hotel', 'Отель', 'City'),
(17,'Hospital', 'Больница', 'City'),
(18,'Airport', 'Аэропорт', 'City'),
(19,'Stadium', 'Стадион', 'City'),
(20,'Restaurant', 'Ресторан', 'City'),
(21,'Building', 'Здание', 'City'),
(22,'Bicycle', 'Велосипед', 'Transportation'),
(23,'Van', 'фургон', 'Transportation'),
(24,'Subway', 'Метро', 'Transportation'),
(25,'Rowing boat', 'Гребная лодка', 'Transportation'),
(26,'Scooter', 'Самокат', 'Transportation'),
(27,'Taxi', 'Такси', 'Transportation'),
(28,'Carriage', 'каретка', 'Transportation'),
(29,'Police car', 'Полицейская машина', 'Transportation'),
(30,'Motorcycle', 'Мотоцикл', 'Transportation'),
(31,'Helicopter', 'Вертолет', 'Transportation'),
(32,'Truck', 'Грузовик', 'Transportation'),
(33,'Fire engine', 'Пожарная машина', 'Transportation'),
(34,'Airplane', 'Самолет', 'Transportation'),
(35,'Ambulance', 'Скорая помощь', 'Transportation'),
(36,'Tractor', 'Трактор', 'Transportation'),
(37,'Crane', 'Кран', 'Transportation'),
(38,'Balloon', 'Воздушный шар', 'Transportation'),
(39,'Bus', 'Автобус', 'Transportation'),
(40,'Train', 'Поезд', 'Transportation'),
(41,'Forklift', 'Вилочный погрузчик', 'Transportation'),
(42,'Boat', 'Лодка', 'Transportation'),
(43,'Car', 'Автомобиль', 'Transportation'),
(44,'Archery', 'Стрельба из лука', 'Sport & Games'),
(45,'Badminton', 'Бадминтон', 'Sport & Games'),
(46,'Cricket', 'Крикет', 'Sport & Games'),
(47,'Bowling', 'Боулинг', 'Sport & Games'),
(48,'Boxing', 'Бокс', 'Sport & Games'),
(49,'Tennis', 'Теннис', 'Sport & Games'),
(50,'Skateboarding', 'Скейтбординг', 'Sport & Games'),
(51,'Surfing', 'Серфинг', 'Sport & Games'),
(52,'Hockey', 'Хоккей', 'Sport & Games'),
(53,'Figure skating', 'Фигурное катание', 'Sport & Games'),
(54,'Yoga', 'Йога', 'Sport & Games'),
(55,'Fencing', 'Фехтование', 'Sport & Games'),
(56,'Fitness', 'Фитнес', 'Sport & Games'),
(57,'Gymnastics', 'Гимнастика', 'Sport & Games'),
(58,'Karate', 'Каратэ', 'Sport & Games'),
(59,'Volleyball', 'Волейбол', 'Sport & Games'),
(60,'Football', 'Футбол', 'Sport & Games'),
(61,'Basketball', 'Баскетбол', 'Sport & Games'),
(62,'Baseball', 'Бейсбол', 'Sport & Games'),
(63,'Rugby', 'Регби', 'Sport & Games'),
(64,'Judo', 'Дзюдо', 'Sport & Games'),
(65,'Table tennis', 'Настольный теннис', 'Sport & Games'),
(66,'Running', 'Бег', 'Sport & Games'),
(67,'Cycling', 'Велоспорт', 'Sport & Games'),
(68,'Giraffe', 'Жираф', 'Animals'),
(69,'Camel', 'Верблюд', 'Animals'),
(70,'Fox', 'Лиса', 'Animals'),
(71,'Horse', 'Лошадь', 'Animals'),
(72,'Sheep', 'Овца', 'Animals'),
(73,'Deer', 'Олень', 'Animals'),
(74,'Koala', 'Коала', 'Animals'),
(75,'Rabbit', 'Кролик', 'Animals'),
(76,'Tiger', 'Тигр', 'Animals'),
(77,'Lion', 'Лев', 'Animals'),
(78,'Kangaroo', 'Кенгуру', 'Animals'),
(79,'Zebra', 'Зебра', 'Animals'),
(80,'Monkey', 'Обезьяна', 'Animals'),
(81,'Panda', 'Панда', 'Animals'),
(82,'Squirrel', 'Белка', 'Animals'),
(83,'Elephant', 'Слон', 'Animals'),
(84,'Leopard', 'Леопард', 'Animals'),
(85,'Wolf', 'Волк', 'Animals'),
(86,'Mouse', 'Мышь', 'Animals'),
(87,'Hedgehog', 'Ежик', 'Animals'),
(88,'Raccoon', 'Енот', 'Animals'),
(89,'Cheetah', 'Гепард', 'Animals'),
(90,'Rhinoceros', 'Носорог', 'Animals'),
(91,'Bear', 'Медведь', 'Animals'),
(92,'Alligator', 'Аллигатор', 'Animals'),
(93,'Buffalo', 'Буйвол', 'Animals'),
(94,'Otter', 'Выдра', 'Animals'),
(95,'Pig', 'Свинья', 'Animals'),
(96,'Cat', 'Кошка', 'Animals'),
(97,'Apple', 'Яблоко', 'Fruits'),
(98,'Apricot', 'Абрикос', 'Fruits'),
(99,'Avocado', 'Авокадо', 'Fruits'),
(100,'Banana', 'Банан', 'Fruits'),
(101,'Blackberry', 'Ежевика', 'Fruits'),
(102,'Blueberry', 'Черника', 'Fruits'),
(103,'Cantaloupe', 'Канталупа', 'Fruits'),
(104,'Cherry', 'Вишня', 'Fruits'),
(105,'Coconut', 'Кокос', 'Fruits'),
(106,'Fig', 'Инжир', 'Fruits'),
(107,'Grapefruit', 'Грейпфрут', 'Fruits'),
(108,'Grape', 'Виноград', 'Fruits'),
(109,'Kiwi', 'Киви', 'Fruits'),
(110,'Lemon', 'Лимон', 'Fruits'),
(111,'Lime', 'Лайм', 'Fruits'),
(112,'Mango', 'Манго', 'Fruits'),
(113,'Melon', 'Дыня', 'Fruits'),
(114,'Orange', 'Апельсин', 'Fruits'),
(115,'Papaya', 'Папайя', 'Fruits'),
(116,'Passion fruit', 'Маракуйя', 'Fruits'),
(117,'Peach', 'Персик', 'Fruits'),
(118,'Pear', 'Груша', 'Fruits'),
(119,'Pineapple', 'Ананас', 'Fruits'),
(120,'Plum', 'Слива', 'Fruits'),
(121,'Pomegranate', 'Гранат', 'Fruits'),
(122,'Raspberry', 'Малина', 'Fruits'),
(123,'Strawberry', 'Клубника', 'Fruits'),
(124,'Cucumber', 'Огурец', 'Vegetables'),
(125,'Onion', 'Лук', 'Vegetables'),
(126,'Garlic', 'Чеснок', 'Vegetables'),
(127,'Carrot', 'Морковь', 'Vegetables'),
(128,'Cabbage', 'Капуста', 'Vegetables'),
(129,'Radish', 'Редис', 'Vegetables'),
(130,'Eggplant', 'Баклажан', 'Vegetables'),
(131,'Mushroom', 'Гриб', 'Vegetables'),
(132,'Pepper', 'Перец', 'Vegetables'),
(133,'Artichoke', 'Артишок', 'Vegetables'),
(134,'Corn', 'Кукуруза', 'Vegetables'),
(135,'Beet', 'Свекла', 'Vegetables'),
(136,'Brocoli', 'Броколи', 'Vegetables'),
(137,'Cauliflower', 'Цветная капуста', 'Vegetables'),
(138,'Celery', 'Сельдерей', 'Vegetables'),
(139,'Chili', 'Чили', 'Vegetables'),
(140,'Potato', 'Картошка', 'Vegetables'),
(141,'Asparagus', 'Спаржа', 'Vegetables'),
(142,'Olives', 'Оливки', 'Vegetables'),
(143,'Pumpkin', 'Тыква', 'Vegetables'),
(144,'Fennel', 'Фенхель', 'Vegetables'),
(145,'Spring Onion', 'Зеленый лук', 'Vegetables'),
(146,'Turnip', 'Репа', 'Vegetables'),
(147,'Green Bean', 'Зеленая фасоль', 'Vegetables'),
(148,'Lettuce', 'Салат', 'Vegetables'),
(149,'Zucchini', 'Кабачки', 'Vegetables'),
(150,'Spinach', 'Шпинат', 'Vegetables'),
(151,'Taro', 'Таро', 'Vegetables'),
(152,'Yam', 'Ям', 'Vegetables'),
(153,'Ginger', 'Имбирь', 'Vegetables'),
(154,'Living room', 'Гостиная', 'House'),
(155,'Kitchen', 'Кухня', 'House'),
(156,'Bathroom', 'Ванная', 'House'),
(157,'Bedroom', 'Спальня', 'House'),
(158,'Attic', 'Чердак', 'House'),
(159,'Garage', 'Гараж', 'House'),
(160,'Dining room', 'Столовая', 'House'),
(161,'Swimming pool', 'Бассейн', 'House'),
(162,'Toilet', 'Туалет', 'House'),
(163,'Sofa', 'Диван', 'House'),
(164,'Armchair', 'Кресло', 'House'),
(165,'Curtains', 'Шторы', 'House'),
(166,'Carpet', 'Ковер', 'House'),
(167,'Fireplace', 'Камин', 'House'),
(168,'Television', 'Телевидение', 'House'),
(169,'Wardbore', 'Шкаф', 'House'),
(170,'Alarm clock', 'Будильник', 'House'),
(171,'Cupboard', 'Шкаф', 'House'),
(172,'Table', 'Стол', 'House'),
(173,'Chair', 'Стул', 'House'),
(174,'Stove', 'Печь', 'House'),
(175,'Regrigerator', 'Холодильник', 'House'),
(176,'Shower', 'Душ', 'House'),
(177,'Bathtub', 'Ванна', 'House'),
(178,'Towels', 'Полотенца', 'House'),
(179,'Washbasin', 'Умывальник', 'House'),
(180,'Radio', 'Радио', 'House'),
(181,'Picture', 'Картина', 'House'),
(182,'Desk', 'Письменный стол', 'House'),
(183,'Computer', 'Компьютер', 'House'),
(184,'Lamp', 'Лампа', 'House'),
(185,'Shelf', 'Полка', 'House'),
(186,'Mother', 'Мать', 'Family'),
(187,'Father', 'Отец', 'Family'),
(188,'Grandparents', 'Бабушка и дедушка', 'Family'),
(189,'Sister', 'Сестра', 'Family'),
(190,'Brother', 'Брат', 'Family'),
(191,'Siblings', 'Братья и сестры', 'Family'),
(192,'Kid', 'Малыш', 'Family'),
(193,'Children', 'Дети', 'Family'),
(194,'Grandmother', 'Бабушка', 'Family'),
(195,'Grandfather', 'Дедушка', 'Family'),
(196,'Daughter', 'Дочь', 'Family'),
(197,'Son', 'Сын', 'Family'),
(198,'Baby', 'Ребенок', 'Family'),
(199,'Cousin', 'Двоюродный брат', 'Family'),
(200,'Uncle', 'Дядя', 'Family'),
(201,'Aunt', 'Тётя', 'Family'),
(202,'Mom', 'Мама', 'Family'),
(203,'Dad', 'Папа', 'Family'),
(204,'Nephew', 'Племянник', 'Family'),
(205,'Niece', 'Племянница', 'Family'),
(206,'Twins', 'Близнецы', 'Family'),
(207,'Shirt', 'Рубашка', 'Clothes'),
(208,'Polo shirt', 'Рубашка-поло', 'Clothes'),
(209,'Jacket', 'Куртка', 'Clothes'),
(210,'Raincoat', 'Плащ', 'Clothes'),
(211,'Jeans', 'Джинсы', 'Clothes'),
(212,'Sweater', 'Свитер', 'Clothes'),
(213,'Scarf', 'Шарф', 'Clothes'),
(214,'Gloves', 'Перчатки', 'Clothes'),
(215,'Tie', 'Галстук', 'Clothes'),
(216,'Dress', 'Платье', 'Clothes'),
(217,'Skirt', 'Юбка', 'Clothes'),
(218,'Sock', 'Носок', 'Clothes'),
(219,'Hat', 'Шляпа', 'Clothes'),
(220,'Suit', 'Костюм', 'Clothes'),
(221,'Shorts', 'Шорты', 'Clothes'),
(222,'Jumper', 'Джемпер', 'Clothes'),
(223,'T-Shirt', 'Футболка', 'Clothes'),
(224,'Trousers', 'Брюки', 'Clothes'),
(225,'Blouse', 'Блузка', 'Clothes'),
(226,'Leggings', 'Леггинсы', 'Clothes'),
(227,'Coat', 'Пальто', 'Clothes'),
(228,'Shoes', 'Обувь', 'Clothes'),
(229,'Slippers', 'Тапочки', 'Clothes'),
(230,'Pyjamas', 'Пижамы', 'Clothes'),
(231,'Flip flops', 'Шлепанцы', 'Clothes'),
(232,'Sunglasses', 'Солнцезащитные очки', 'Clothes'),
(233,'Belt', 'Ремень', 'Clothes'),
(234,'Cardigan', 'Кардиган', 'Clothes'),
(235,'Cap', 'Кепка', 'Clothes'),
(236,'Bowtie', 'Галстук-бабочка', 'Clothes'),
(237,'Overall', 'Комбинезон', 'Clothes'),
(238,'Bread', 'Хлеб', 'Food & Drinks'),
(239,'Bagel', 'Бублик', 'Food & Drinks'),
(240,'Cheese', 'Сыр', 'Food & Drinks'),
(241,'Olive', 'Оливковое', 'Food & Drinks'),
(242,'Butter', 'Сливочное масло', 'Food & Drinks'),
(243,'Egg', 'Яйцо', 'Food & Drinks'),
(244,'Honey', 'Мед', 'Food & Drinks'),
(245,'Jam', 'Джем', 'Food & Drinks'),
(246,'Sausage', 'Колбаса', 'Food & Drinks'),
(247,'Salami', 'Салями', 'Food & Drinks'),
(248,'Meat', 'Мясо', 'Food & Drinks'),
(249,'Chicken', 'Курица', 'Food & Drinks'),
(250,'Fish', 'Рыба', 'Food & Drinks'),
(251,'Chips', 'Чипсы', 'Food & Drinks'),
(252,'Hamburger', 'Гамбургер', 'Food & Drinks'),
(253,'Sandwich', 'Сэндвич', 'Food & Drinks'),
(254,'Pizza', 'Пицца', 'Food & Drinks'),
(255,'Soup', 'Суп', 'Food & Drinks'),
(256,'Popcorn', 'Попкорн', 'Food & Drinks'),
(257,'Cake', 'Торт', 'Food & Drinks'),
(258,'Cookie', 'Печенье', 'Food & Drinks'),
(259,'Ice-cream', 'Мороженое', 'Food & Drinks'),
(260,'Chocolate', 'Шоколад', 'Food & Drinks'),
(261,'Candy', 'Конфеты', 'Food & Drinks'),
(262,'Juice', 'Сок', 'Food & Drinks'),
(263,'Water', 'Вода', 'Food & Drinks'),
(264,'Milk', 'Молоко', 'Food & Drinks'),
(265,'Wine', 'Вино', 'Food & Drinks'),
(266,'Green tea', 'Зеленый чай', 'Food & Drinks'),
(267,'Lemonade', 'Лимонад', 'Food & Drinks'),
(268,'Cola', 'Кола', 'Food & Drinks'),
(269,'Coffee', 'Кофе', 'Food & Drinks'),
(270,'Beer', 'Пиво', 'Food & Drinks'),
(271,'Soda', 'Газировка', 'Food & Drinks'),
(272, 'Mathematics', 'Математика', 'Education'),
(273, 'Science', 'Наука', 'Education'),
(274, 'Literature', 'Литература', 'Education'),
(275, 'History', 'История', 'Education'),
(276, 'Geography', 'География', 'Education'),
(277, 'Algebra', 'Алгебра', 'Education'),
(278, 'Biology', 'Биология', 'Education'),
(279, 'Chemistry', 'Химия', 'Education'),
(280, 'Physics', 'Физика', 'Education'),
(281, 'Computer Science', 'Информатика', 'Education'),
(282, 'Art', 'Искусство', 'Education'),
(283, 'Music', 'Музыка', 'Education'),
(284, 'Physical Education', 'Физическая культура', 'Education'),
(285, 'English', 'Английский язык', 'Education'),
(286, 'Language Arts', 'Литературное искусство', 'Education'),
(287, 'Student', 'Студент', 'Education'),
(288, 'Teacher', 'Учитель', 'Education'),
(289, 'Classroom', 'Класс', 'Education'),
(290, 'Homework', 'Домашнее задание', 'Education'),
(291, 'Examination', 'Экзамен', 'Education'),
(292, 'Textbook', 'Учебник', 'Education'),
(293, 'Library', 'Библиотека', 'Education'),
(294, 'Graduation', 'Выпуск', 'Education'),
(295, 'Degree', 'Степень', 'Education'),
(296, 'Learning', 'Обучение', 'Education'),
(297, 'Clock', 'Часы', 'Time'),
(298, 'Hour', 'Час', 'Time'),
(299, 'Minute', 'Минута', 'Time'),
(300, 'Second', 'Секунда', 'Time'),
(301, 'Day', 'День', 'Time'),
(302, 'Week', 'Неделя', 'Time'),
(303, 'Month', 'Месяц', 'Time'),
(304, 'Year', 'Год', 'Time'),
(305, 'Yesterday', 'Вчера', 'Time'),
(306, 'Today', 'Сегодня', 'Time'),
(307, 'Tomorrow', 'Завтра', 'Time'),
(308, 'Morning', 'Утро', 'Time'),
(309, 'Afternoon', 'День', 'Time'),
(310, 'Evening', 'Вечер', 'Time'),
(311, 'Night', 'Ночь', 'Time'),
(312, 'Clockwise', 'По часовой стрелке', 'Time'),
(313, 'Counterclockwise', 'Против часовой стрелки', 'Time'),
(314, 'Past', 'После', 'Time'),
(315, 'Present', 'Настоящее', 'Time'),
(316, 'Future', 'Будущее', 'Time'),
(317, 'Monday', 'Понедельник', 'Days of the Week'),
(318, 'Tuesday', 'Вторник', 'Days of the Week'),
(319, 'Wednesday', 'Среда', 'Days of the Week'),
(320, 'Thursday', 'Четверг', 'Days of the Week'),
(321, 'Friday', 'Пятница', 'Days of the Week'),
(322, 'Saturday', 'Суббота', 'Days of the Week'),
(323, 'Sunday', 'Воскресенье', 'Days of the Week'),
(324, 'Kyrgyzstan', 'Кыргызстан', 'Countries'),
(325, 'United States', 'Соединенные Штаты', 'Countries'),
(326, 'China', 'Китай', 'Countries'),
(327, 'India', 'Индия', 'Countries'),
(328, 'Brazil', 'Бразилия', 'Countries'),
(329, 'France', 'Франция', 'Countries'),
(330, 'Germany', 'Германия', 'Countries'),
(331, 'Japan', 'Япония', 'Countries'),
(332, 'Canada', 'Канада', 'Countries'),
(333, 'Australia', 'Австралия', 'Countries'),
(334, 'United Kingdom', 'Соединенное Королевство', 'Countries'),
(335, 'South Africa', 'Южная Африка', 'Countries'),
(336, 'Mexico', 'Мексика', 'Countries'),
(337, 'Italy', 'Италия', 'Countries'),
(338, 'Spain', 'Испания', 'Countries'),
(339, 'South Korea', 'Южная Корея', 'Countries'),
(340, 'Argentina', 'Аргентина', 'Countries'),
(341, 'Nigeria', 'Нигерия', 'Countries'),
(342, 'Saudi Arabia', 'Саудовская Аравия', 'Countries'),
(343, 'Egypt', 'Египет', 'Countries'),
(344, 'January', 'Январь', 'Months'),
(345, 'February', 'Февраль', 'Months'),
(346, 'March', 'Март', 'Months'),
(347, 'April', 'Апрель', 'Months'),
(348, 'May', 'Май', 'Months'),
(349, 'June', 'Июнь', 'Months'),
(350, 'July', 'Июль', 'Months'),
(351, 'August', 'Август', 'Months'),
(352, 'September', 'Сентябрь', 'Months'),
(353, 'October', 'Октябрь', 'Months'),
(354, 'November', 'Ноябрь', 'Months'),
(355, 'December', 'Декабрь', 'Months'),
(356, 'Head', 'Голова', 'Body Parts'),
(357, 'Hair', 'Волосы', 'Body Parts'),
(358, 'Eyes', 'Глаза', 'Body Parts'),
(359, 'Ears', 'Уши', 'Body Parts'),
(360, 'Nose', 'Нос', 'Body Parts'),
(361, 'Mouth', 'Рот', 'Body Parts'),
(362, 'Teeth', 'Зубы', 'Body Parts'),
(363, 'Tongue', 'Язык', 'Body Parts'),
(364, 'Neck', 'Шея', 'Body Parts'),
(365, 'Shoulder', 'Плечо', 'Body Parts'),
(366, 'Arm', 'Рука', 'Body Parts'),
(367, 'Elbow', 'Локоть', 'Body Parts'),
(368, 'Hand', 'Рука (кисть)', 'Body Parts'),
(369, 'Fingers', 'Пальцы', 'Body Parts'),
(370, 'Chest', 'Грудь', 'Body Parts'),
(371, 'Back', 'Спина', 'Body Parts'),
(372, 'Stomach', 'Живот', 'Body Parts'),
(373, 'Leg', 'Нога', 'Body Parts'),
(374, 'Knee', 'Колено', 'Body Parts'),
(375, 'Foot', 'Нога (стопа)', 'Body Parts'),
(376, 'Toes', 'Пальцы на ногах', 'Body Parts'),
(377, 'Music', 'Музыка', 'Music'),
(378, 'Song', 'Песня', 'Music'),
(379, 'Instrument', 'Инструмент', 'Music'),
(380, 'Guitar', 'Гитара', 'Music'),
(381, 'Piano', 'Пианино', 'Music'),
(382, 'Drums', 'Барабаны', 'Music'),
(383, 'Singer', 'Певец/певица', 'Music'),
(384, 'Concert', 'Концерт', 'Music'),
(385, 'Album', 'Альбом', 'Music'),
(386, 'Melody', 'Мелодия', 'Music'),
(387, 'Dance', 'Танец', 'Music'),
(388, 'Rhythm', 'Ритм', 'Music'),
(389, 'Lyrics', 'Текст песни', 'Music'),
(390, 'Genre', 'Жанр', 'Music'),
(391, 'Orchestra', 'Оркестр', 'Music'),
(392, 'Holiday', 'Праздник', 'Holidays'),
(393, 'Christmas', 'Рождество', 'Holidays'),
(394, 'New Year', 'Новый год', 'Holidays'),
(395, 'Easter', 'Пасха', 'Holidays'),
(396, 'Thanksgiving', 'День благодарения', 'Holidays'),
(397, 'Birthday', 'День рождения', 'Holidays'),
(398, 'Halloween', 'Хэллоуин', 'Holidays'),
(399, 'Independence Day', 'День независимости', 'Holidays'),
(400, 'Valentine', 'День Святого Валентина', 'Holidays'),
(401, 'Labor Day', 'День труда', 'Holidays'),
(402, 'National Day', 'Национальный день', 'Holidays'),
(403, 'Hobby', 'Хобби', 'Hobbies'),
(404, 'Reading', 'Чтение', 'Hobbies'),
(405, 'Writing', 'Письмо', 'Hobbies'),
(406, 'Drawing', 'Рисование', 'Hobbies'),
(407, 'Painting', 'Живопись', 'Hobbies'),
(408, 'Photography', 'Фотография', 'Hobbies'),
(409, 'Cooking', 'Готовка', 'Hobbies'),
(410, 'Gardening', 'Садоводство', 'Hobbies'),
(411, 'Traveling', 'Путешествие', 'Hobbies'),
(412, 'Collecting', 'Коллекционирование', 'Hobbies'),
(413, 'Sports', 'Спорт', 'Hobbies'),
(414, 'Gaming', 'Игры', 'Hobbies'),
(415, 'Music Listening', 'Прослушивание музыки', 'Hobbies'),
(416, 'DIY (Do It Yourself)', 'Сделай сам', 'Hobbies'),
(417, 'Weather', 'Погода', 'Weather'),
(418, 'Sun', 'Солнце', 'Weather'),
(419, 'Cloud', 'Облако', 'Weather'),
(420, 'Rain', 'Дождь', 'Weather'),
(421, 'Snow', 'Снег', 'Weather'),
(422, 'Wind', 'Ветер', 'Weather'),
(423, 'Storm', 'Шторм', 'Weather'),
(424, 'Thunder', 'Гроза', 'Weather'),
(425, 'Lightning', 'Молния', 'Weather'),
(426, 'Temperature', 'Температура', 'Weather'),
(427, 'Humidity', 'Влажность', 'Weather'),
(428, 'Season', 'Сезон', 'Weather'),
(429, 'Spring', 'Весна', 'Weather'),
(430, 'Summer', 'Лето', 'Weather'),
(431, 'Autumn', 'Осень', 'Weather'),
(432, 'Winter', 'Зима', 'Weather'),
(433, 'Plants', 'Растения', 'Plants'),
(434, 'Flower', 'Цветок', 'Plants'),
(435, 'Tree', 'Дерево', 'Plants'),
(436, 'Grass', 'Трава', 'Plants'),
(437, 'Bush', 'Куст', 'Plants'),
(438, 'Leaf', 'Лист', 'Plants'),
(439, 'Root', 'Корень', 'Plants'),
(440, 'Fruit', 'Плод', 'Plants'),
(441, 'Vegetable', 'Овощ', 'Plants'),
(442, 'Seed', 'Семя', 'Plants'),
(443, 'Garden', 'Сад', 'Plants'),
(444, 'Floral', 'Цветочный', 'Plants'),
(445, 'Furniture', 'Мебель', 'Furniture'),
(446, 'Chair', 'Стул', 'Furniture'),
(447, 'Table', 'Стол', 'Furniture'),
(448, 'Sofa', 'Диван', 'Furniture'),
(449, 'Bed', 'Кровать', 'Furniture'),
(450, 'Wardrobe', 'Шкаф', 'Furniture'),
(451, 'Shelf', 'Полка', 'Furniture'),
(452, 'Cabinet', 'Шкаф/кабинет', 'Furniture'),
(453, 'Mirror', 'Зеркало', 'Furniture'),
(454, 'Lamp', 'Лампа', 'Furniture'),
(455, 'Desk', 'Письменный стол', 'Furniture'),
(456, 'Bookcase', 'Книжный шкаф', 'Furniture'),
(457, 'Drawer', 'Ящик', 'Furniture'),
(458, 'Sofa Bed', 'Раскладной диван', 'Furniture'),
(459, 'Film', 'Фильм', 'Cinema'),
(460, 'Actor', 'Актер', 'Cinema'),
(461, 'Actress', 'Актриса', 'Cinema'),
(462, 'Director', 'Режиссер', 'Cinema'),
(463, 'Screenplay', 'Сценарий', 'Cinema'),
(464, 'Cinematography', 'Кинематография', 'Cinema'),
(465, 'Genre', 'Жанр', 'Cinema'),
(466, 'Plot', 'Сюжет', 'Cinema'),
(467, 'Scene', 'Сцена', 'Cinema'),
(468, 'Dialogue', 'Диалог', 'Cinema'),
(469, 'Soundtrack', 'Саундтрек', 'Cinema'),
(470, 'Special Effects', 'Спецэффекты', 'Cinema'),
(471, 'Award', 'Награда', 'Cinema'),
(472, 'Cinema Hall', 'Кинозал', 'Cinema'),
(473, 'Painting', 'Живопись', 'Art'),
(474, 'Canvas', 'Холст', 'Art'),
(475, 'Palette', 'Палитра', 'Art'),
(476, 'Brush', 'Кисть', 'Art'),
(477, 'Easel', 'Мольберт', 'Art'),
(478, 'Portrait', 'Портрет', 'Art'),
(479, 'Landscape', 'Пейзаж', 'Art'),
(480, 'Still Life', 'Натюрморт', 'Art'),
(481, 'Abstract Art', 'Абстрактное искусство', 'Art'),
(482, 'Watercolor', 'Акварель', 'Art'),
(483, 'Oil Painting', 'Живопись маслом', 'Art'),
(484, 'Sculpture', 'Скульптура', 'Art'),
(485, 'Literature', 'Литература', 'Literature'),
(486, 'Book', 'Книга', 'Literature'),
(487, 'Author', 'Автор', 'Literature'),
(488, 'Novel', 'Роман', 'Literature'),
(489, 'Poetry', 'Поэзия', 'Literature'),
(490, 'Short Story', 'Рассказ', 'Literature'),
(491, 'Genre', 'Жанр', 'Literature'),
(492, 'Plot', 'Сюжет', 'Literature'),
(493, 'Character', 'Персонаж', 'Literature'),
(494, 'Setting', 'Сюжетная обстановка', 'Literature'),
(495, 'Protagonist', 'Протагонист', 'Literature'),
(496, 'Antagonist', 'Антагонист', 'Literature'),
(497, 'Chapter', 'Глава', 'Literature'),
(498, 'Poet', 'Поэт', 'Literature');